### ISSUE TITLE
API fora do Ar

### ISSUE THREAD

**Issue by karlos-oliveira** [giorgiolucca/fipe#1]
A api hospedada no fipeapi.appspot esta fora provavelmente por conta da cota excedida, poderia disponibilizar o código da API? pois como a SDK depende da API para funcionar seria legal poder hospedar os 2 em outro servidor para não ter esses problemas de cota excedida.

**Comment by giorgiolucca** [comment]
@karlos-oliveira infelizmente eu não tenho acesso ao código da API, vou tentar entrar em contato com os responsáveis pra acharmos uma solução para que isso não ocorra novamente
